name: imperative_flutter
description: Manage the state of your widgets using imperative programming concepts.
version: 1.0.0
repository: https://github.com/JunioJsv/imperative-flutter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
