name: imperative_flutter
description: Manage the state of your widgets using simple id.
version: 0.0.1
repository: https://github.com/JunioJsv/imperative-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
